### ISSUE TITLE
Cannot run ng-xi18n

### ISSUE THREAD

**Issue by reynardmh** [StephenFluin/i18n-sample#6]
I tried running ng-xi18n and get the following error: 

```
$ ./node_modules/.bin/ng-xi18n
can't resolve module @angular/core/src/di/metadata from /i18n-sample/index.ts
Error: can't find symbol Host exported from module /i18n-sample/node_modules/@angular/core/src/di/metadata.d.ts
    at ReflectorHost.findDeclaration (/i18n-sample/node_modules/@angular/compiler-cli/src/reflector_host.js:173:23)
    at StaticReflector.initializeConversionMap (/i18n-sample/node_modules/@angular/compiler-cli/src/static_reflector.js:147:55)
    at new StaticReflector (/i18n-sample/node_modules/@angular/compiler-cli/src/static_reflector.js:42:14)
    at Function.Extractor.create (/i18n-sample/node_modules/@angular/compiler-cli/src/extract_i18n.js:133:31)
    at extract (/i18n-sample/node_modules/@angular/compiler-cli/src/extract_i18n.js:15:31)
    at Object.main (/i18n-sample/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/i18n-sample/node_modules/@angular/compiler-cli/src/extract_i18n.js:160:9)
```

How do you extract the message into xliff file?

**Comment by reynardmh** [comment]
For people getting stumbled with this sample app, I recommend using another sample app by Klaas: http://klaascuvelier.io/2016/09/internationalization-in-angular2/

The sample app there works (follow the instruction on the blog).
