### ISSUE TITLE
error while running npm start

### ISSUE THREAD

**Issue by epadma** [StephenFluin/i18n-sample#8]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm start

> dashboard@0.0.0 start C:\Users\padmavathi\Downloads\phototype-development\web\
dashboard
> ng serve

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\padmavathi\Downloads\phototype-development\web
\dashboard\node_modules\typescript\lib\typescript.js:14571:109)
    at parseSourceFileWorker (C:\Users\padmavathi\Downloads\phototype-developmen
t\web\dashboard\node_modules\typescript\lib\typescript.js:14503:26)
    at Object.parseSourceFile (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\typescript\lib\typescript.js:14452:26)
    at Object.createSourceFile (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\typescript\lib\typescript.js:14307:29)
    at new TypeScriptFileRefactor (C:\Users\padmavathi\Downloads\phototype-devel
opment\web\dashboard\node_modules\@ngtools\webpack\src\refactor.js:25:35)
    at Object.resolveEntryModuleFromMain (C:\Users\padmavathi\Downloads\phototyp
e-development\web\dashboard\node_modules\@ngtools\webpack\src\entry_resolver.js:
108:18)
    at AotPlugin._setupOptions (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\@ngtools\webpack\src\plugin.js:129:58)
    at new AotPlugin (C:\Users\padmavathi\Downloads\phototype-development\web\da
shboard\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (C:\Users\padmavathi\Downloa
ds\phototype-development\web\dashboard\node_modules\angular-cli\models\webpack-b
uild-typescript.js:20:13)
    at new NgCliWebpackConfig (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (C:\Users\padmavathi\Downloads\phototype-development\web\dashbo
ard\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\node_mo
dules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm install -g
 http-server
C:\Users\padmavathi\AppData\Roaming\npm\hs -> C:\Users\padmavathi\AppData\Roamin
g\npm\node_modules\http-server\bin\http-server
C:\Users\padmavathi\AppData\Roaming\npm\http-server -> C:\Users\padmavathi\AppDa
ta\Roaming\npm\node_modules\http-server\bin\http-server
C:\Users\padmavathi\AppData\Roaming\npm
`-- http-server@0.9.0

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm start

> dashboard@0.0.0 start C:\Users\padmavathi\Downloads\phototype-development\web\
dashboard
> ng serve

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\padmavathi\Downloads\phototype-development\web
\dashboard\node_modules\typescript\lib\typescript.js:14571:109)
    at parseSourceFileWorker (C:\Users\padmavathi\Downloads\phototype-developmen
t\web\dashboard\node_modules\typescript\lib\typescript.js:14503:26)
    at Object.parseSourceFile (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\typescript\lib\typescript.js:14452:26)
    at Object.createSourceFile (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\typescript\lib\typescript.js:14307:29)
    at new TypeScriptFileRefactor (C:\Users\padmavathi\Downloads\phototype-devel
opment\web\dashboard\node_modules\@ngtools\webpack\src\refactor.js:25:35)
    at Object.resolveEntryModuleFromMain (C:\Users\padmavathi\Downloads\phototyp
e-development\web\dashboard\node_modules\@ngtools\webpack\src\entry_resolver.js:
108:18)
    at AotPlugin._setupOptions (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\@ngtools\webpack\src\plugin.js:129:58)
    at new AotPlugin (C:\Users\padmavathi\Downloads\phototype-development\web\da
shboard\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (C:\Users\padmavathi\Downloa
ds\phototype-development\web\dashboard\node_modules\angular-cli\models\webpack-b
uild-typescript.js:20:13)
    at new NgCliWebpackConfig (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (C:\Users\padmavathi\Downloads\phototype-development\web\dashbo
ard\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\node_mo
dules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm start

> dashboard@0.0.0 start C:\Users\padmavathi\Downloads\phototype-development\web\
dashboard
> ng serve

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\padmavathi\Downloads\phototype-development\web
\dashboard\node_modules\typescript\lib\typescript.js:14571:109)
    at parseSourceFileWorker (C:\Users\padmavathi\Downloads\phototype-developmen
t\web\dashboard\node_modules\typescript\lib\typescript.js:14503:26)
    at Object.parseSourceFile (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\typescript\lib\typescript.js:14452:26)
    at Object.createSourceFile (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\typescript\lib\typescript.js:14307:29)
    at new TypeScriptFileRefactor (C:\Users\padmavathi\Downloads\phototype-devel
opment\web\dashboard\node_modules\@ngtools\webpack\src\refactor.js:25:35)
    at Object.resolveEntryModuleFromMain (C:\Users\padmavathi\Downloads\phototyp
e-development\web\dashboard\node_modules\@ngtools\webpack\src\entry_resolver.js:
108:18)
    at AotPlugin._setupOptions (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\@ngtools\webpack\src\plugin.js:129:58)
    at new AotPlugin (C:\Users\padmavathi\Downloads\phototype-development\web\da
shboard\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (C:\Users\padmavathi\Downloa
ds\phototype-development\web\dashboard\node_modules\angular-cli\models\webpack-b
uild-typescript.js:20:13)
    at new NgCliWebpackConfig (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (C:\Users\padmavathi\Downloads\phototype-development\web\dashbo
ard\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\node_mo
dules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>^A

**Comment by iAakashTomar** [comment]
run npm install first
